### ISSUE TITLE
Master showing 0% even after RecordMasterCoverage is run

### ISSUE THREAD

**Issue by technolo-g** [jenkinsci/github-pr-coverage-status-plugin#30]
After the upgrade to 1.8.1, our master coverage began reporting as 0%. This seems to be caused by using different methods to store and retrieve the data in the master coverage map. I can't be sure if it is specific to GitHub Enterprise, but that is what we are using. 

The issue appears to be here:
https://github.com/jenkinsci/github-pr-coverage-status-plugin/commit/a66d77b65f0fe442253d2ed1d7a5e95029d570c9#diff-22ca09200b10d3f4df393e13a098a24eR33

It is doing a lookup on `repo-name`, but our repo name is stored in the map as `git@ghe.domain.com/repo-name`. When passing the FQRN (`git@ghe.domain.com/repo-name`) the proper coverage value comes back.

Steps to reproduce:
- Run a job that adds master coverage
- Open the script console
- confirm the entry is there:
```
import com.github.terma.jenkins.githubprcoveragestatus.*

com.github.terma.jenkins.githubprcoveragestatus.Configuration.ConfigurationDescriptor blah = new com.github.terma.jenkins.githubprcoveragestatus.Configuration.ConfigurationDescriptor()

println(blah.getCoverageByRepo())
```
- Check org/repo-name:
```
import com.github.terma.jenkins.githubprcoveragestatus.*
  
com.github.terma.jenkins.githubprcoveragestatus.Configuration.ConfigurationDescriptor blah = new com.github.terma.jenkins.githubprcoveragestatus.Configuration.ConfigurationDescriptor()

println(blah.getCoverageByRepo().get("repo-name"))
```
- comes back null
- check by FQRN
```
import com.github.terma.jenkins.githubprcoveragestatus.*
  
com.github.terma.jenkins.githubprcoveragestatus.Configuration.ConfigurationDescriptor blah = new com.github.terma.jenkins.githubprcoveragestatus.Configuration.ConfigurationDescriptor()

println(blah.getCoverageByRepo().get("git@ghe.domain.com:org/repo-name.git"))
```
- comes back with valid float

**Comment by Andriy-Sorochak** [comment]
Same problem with non-enterprise repo specified as `git@github.com:organization/repo-name.git`: it's stored into master coverage map as `git@github.com:organization/repo-name.git` but later trying to retrieve by key `repo-name`

**Comment by terma** [comment]
@technolo-g @Andriy-Sorochak  I can try to fix as soon back from vacation =) so after one week.

**Comment by mesolimbo** [comment]
+1

**Comment by aliyakamercan** [comment]
+1

**Comment by mesolimbo** [comment]
(Thanks for the plugin BTW 😄 )

**Comment by jhensley** [comment]
+1

**Comment by terma** [comment]
Fix in #31

**Comment by technolo-g** [comment]
Thanks man!

**Comment by terma** [comment]
@technolo-g @jhensley @mesolimbo @Andriy-Sorochak @aliyakamercan Please try fix [1.8.2](https://github.com/jenkinsci/github-pr-coverage-status-plugin/releases/tag/github-pr-coverage-status-1.8.2)

**Comment by aliyakamercan** [comment]
thanks!

**Comment by mesolimbo** [comment]
Fix confirmed, youdabest! =)
