### ISSUE TITLE
Discover PR URL via GH API to support BRANCH builds in multi-branch

### ISSUE THREAD

**Issue by jayv** [jenkinsci/github-pr-coverage-status-plugin#33]
We're using the Multibranch plugin but can't use PR builds for various reasons, so we only have branch builds turned on. It which works well in github, commits get the green checkmarks, PRs get approved for merging etc.... 
Except this plugin is broken because it expects CHANGE_URL to be set. It would be nice to have an option to use https://developer.github.com/v3/pulls/#list-pull-requests for branch builds to discover associated PRs and still get the same functionality.

It looks like  it's not that much work and may contribute a PR for this.

**Comment by jayv** [comment]
Here is a PR that enables PR comments with branch-only builds with Github Branch Source Plugin, guarded by a feature-flag:

https://github.com/jenkinsci/github-pr-coverage-status-plugin/pull/34

I'm not very familiar with jenkins plugin development, so feel free to point out issues with this.

**Comment by terma** [comment]
@jayv sorry for delay and thx for contribution, released under version [1.9.0](https://github.com/jenkinsci/github-pr-coverage-status-plugin/releases/tag/github-pr-coverage-status-1.9.0)
