### ISSUE TITLE
Replacement vs creation of comments

### ISSUE THREAD

**Issue by Mokto** [jenkinsci/github-pr-coverage-status-plugin#51]
Hi,

Would it be possible to replace the previous comment instead of creating one each time ?

![screen shot 2018-01-15 at 10 31 48 am](https://user-images.githubusercontent.com/5103928/34949856-5e04c6be-f9df-11e7-9d36-f3cbb17748d3.png)

I would like to avoid this behavior.

Thanks !

**Comment by terma** [comment]
@Mokto I think that possible, let me check

**Comment by Mokto** [comment]
Hey,

Any news on this ?

Thanks !

**Comment by gouraharidas** [comment]
Instead of creating a comment everytime, it would be great if we can put it here.

![image](https://user-images.githubusercontent.com/38141950/40091248-6315048a-586b-11e8-912c-c0bf78f610e1.png)

**Comment by dmotpan** [comment]
GH-64 GH-65
