### ISSUE TITLE
Jacoco version 0.8

### ISSUE THREAD

**Issue by stuarthendren** [jenkinsci/github-pr-coverage-status-plugin#59]
It would be good to update the jacoco version to get eh improved features it has eg Java 9, Java 10 (0.8.1) and lombok generated support.

**Comment by terma** [comment]
Looks like Jacoco Jenkins Plugin uses it as well https://www.jacoco.org/jacoco/trunk/doc/changes.html

**Comment by terma** [comment]
Coverage plugin doesn't depends on Jacoco, instead it uses report generated by Jenkins Jacoco Plugin or plugin from your app maven conf, as result if you want to increase version just update it.
