### ISSUE TITLE
status check reporting success on coverage drop

### ISSUE THREAD

**Issue by tburow** [jenkinsci/github-pr-coverage-status-plugin#75]
Im getting a successful status check reported in Github when the coverage drops, im expecting a failed check.

[GitHub PR Status] master coverage: 0.496
[GitHub PR Status] collecting coverage...
[GitHub PR Status] build coverage: 0.47907975
[GitHub PR Status] Coverage 48% changed -1.69% vs master 50%
[GitHub PR Status] publishing result as status check
<img width="553" alt="image" src="https://user-images.githubusercontent.com/23199535/62725134-ca02df00-b9d1-11e9-8382-44ca7c02d812.png">

pipeline stage
stage('PR Coverage to Github') {
            when { allOf {not { branch 'master' }; expression { return env.CHANGE_ID != null }} }
            steps {
                script {
                    currentBuild.result = 'SUCCESS'
                 }
                step([$class: 'CompareCoverageAction',
                              publishResultAs: 'statusCheck',
                              scmVars: [GIT_URL: env.GIT_URL]])
            }
        }

**Comment by dmotpan** [comment]
@tburow currently, the status check reported is always a success, but it will be reporting a failure in the next release of the plugin

**Comment by storpeyCHT** [comment]
I see the change to support this is merged.  Any ETA on when the release will be out?

**Comment by dmotpan** [comment]
@tburow @storpeyCHT A new version of the plugin with this feature has been released
